#include <Arduino.h> // L0001
#include <vector> // L0002
// L0003
// L0004
// Runtime helpers generated by transpiler // L0005
static std::vector<String> __vb_split(const String& input, const String& delim) { // L0006
    std::vector<String> parts; // L0007
    int start = 0; // L0008
    int idx = 0; // L0009
    if (delim.length() == 0) { parts.push_back(input); return parts; } // L0010
    while ((idx = input.indexOf(delim, start)) != -1) { // L0011
        parts.push_back(input.substring(start, idx)); // L0012
        start = idx + delim.length(); // L0013
    } // L0014
    parts.push_back(input.substring(start)); // L0015
    return parts; // L0016
} // L0017
// L0018
static String __vb_join(const std::vector<String>& parts, const String& delim) { // L0019
    String out = ""; // L0020
    for (size_t i = 0; i < parts.size(); ++i) { // L0021
        out += parts[i]; // L0022
        if (i + 1 < parts.size()) out += delim; // L0023
    } // L0024
    return out; // L0025
} // L0026
// L0027
static std::vector<String> __vb_filter(const std::vector<String>& parts, const String& match) { // L0028
    std::vector<String> out; // L0029
    for (const auto& p : parts) { // L0030
        if (p.indexOf(match) != -1) out.push_back(p); // L0031
    } // L0032
    return out; // L0033
} // L0034
// L0035
// L0036
// L0037
void setup() { // L0038
    delay(1000); // L0039
    // __VB_LINE__:5 // L0040
    Serial.begin(115200); // L0041
    Serial.setRxBufferSize(1024); // L0042
    Serial.setTxBufferSize(1024); // L0043
    // __VB_LINE__:6 // L0044
    Serial.println("Split/Join/Filter demo"); // L0045
    // __VB_LINE__:8 // L0046
    String text = ""; // L0047
    // __VB_LINE__:9 // L0048
    text = "red,green,blue,orange,grape,banana"; // L0049
    // __VB_LINE__:12 // L0050
    Auto parts; // L0051
    // __VB_LINE__:13 // L0052
    parts = __vb_split(String(text), String(",")); // L0053
    // __VB_LINE__:15 // L0054
    Auto filtered; // L0055
    // __VB_LINE__:16 // L0056
    filtered = __vb_filter(parts, String("an")); // L0057
    // __VB_LINE__:18 // L0058
    String joined = ""; // L0059
    // __VB_LINE__:19 // L0060
    joined = __vb_join(filtered, String(" | ")); // L0061
    // __VB_LINE__:21 // L0062
    Serial.println("Filtered items:"); // L0063
    // __VB_LINE__:22 // L0064
    for (auto& item : filtered) { // L0065
    // __VB_LINE__:23 // L0066
    Serial.println("  - " + item); // L0067
    // __VB_LINE__:24 // L0068
    } // L0069
    // __VB_LINE__:25 // L0070
    Serial.println("Joined: " + joined); // L0071
    // __VB_LINE__:28 // L0072
    int day = 0; // L0073
    // __VB_LINE__:29 // L0074
    day = 3; // L0075
    // __VB_LINE__:30 // L0076
    String dayName = ""; // L0077
    // __VB_LINE__:31 // L0078
    dayName = ((day)==1?"Mon":((day)==2?"Tue":((day)==3?"Wed":((day)==4?"Thu":((day)==5?"Fri":((day)==6?"Sat":((day)==7?"Sun":String(""))); // L0079
    // __VB_LINE__:32 // L0080
    Serial.println("Day 3 -> " + dayName); // L0081
    // __VB_LINE__:35 // L0082
    int score = 0; // L0083
    // __VB_LINE__:36 // L0084
    score = 72; // L0085
    // __VB_LINE__:37 // L0086
    String grade = ""; // L0087
    // __VB_LINE__:38 // L0088
    grade = (score < 60?"F":(score < 70?"D":(score < 80?"C":(score < 90?"B":(true?"A":String(""))); // L0089
    // __VB_LINE__:39 // L0090
    Serial.println("Score 72 -> " + grade); // L0091
    // __VB_LINE__:42 // L0092
    randomSeed(millis()); // L0093
    // __VB_LINE__:43 // L0094
    long startTick = 0; // L0095
    // __VB_LINE__:44 // L0096
    startTick = millis(); // L0097
    // __VB_LINE__:45 // L0098
    int randomVal = 0; // L0099
    // __VB_LINE__:46 // L0100
    randomVal = random[0][32767]; // L0101
    // __VB_LINE__:47 // L0102
    Serial.println("Random value: " + randomVal); // L0103
    // __VB_LINE__:48 // L0104
    long elapsed = 0; // L0105
    // __VB_LINE__:49 // L0106
    elapsed = millis() - startTick; // L0107
    // __VB_LINE__:50 // L0108
    Serial.println("Elapsed ms: " + elapsed); // L0109
    // __VB_LINE__:53 // L0110
    { // With Serial // L0111
    // __VB_LINE__:54 // L0112
    Serial.println("With block works"); // L0113
    // __VB_LINE__:55 // L0114
    } // L0115
    // __VB_LINE__:57 // L0116
    Serial.println("Done"); // L0117
} // L0118
// L0119
void loop() { // L0120
     // L0121
} // L0122
