"""Descriptions for completion items shown in the editor completer tooltips."""

DESCRIPTIONS = {
    "#Include": "Include header/library (transpiler directive).\nUsage: #Include \"WiFi.h\"",
    "#Define": "Define constant or macro (transpiler directive).\nUsage: #Define BAUD 115200",
    "Dim": "Declare variable or array.\nUsage: Dim i As Integer, a() As String",
    "ReDim": "Resize dynamic array (preserves with 'Preserve').\nUsage: ReDim Preserve a(0 To 9)",
    "As": "Type annotation for variables and parameters.",
    "ByVal": "Pass parameter by value (default).",
    "ByRef": "Pass parameter by reference.\nUsage: Sub Swap(ByRef a As Integer, ByRef b As Integer)",
    "Optional": "Optional parameter with default value.\nUsage: Sub Log(msg As String, Optional level As Integer = 1)",
    "Const": "Define compile-time constant.\nUsage: Const Pi As Double = 3.14159",
    "If": "Conditional branching.\nUsage: If x > 0 Then ...",
    "ElseIf": "Conditional branching (additional condition).",
    "Else": "Conditional branching (fallback).",
    "End If": "Terminate If block.",
    "Select Case": "Multi-branch selection based on expression.\nUsage:\nSelect Case x\n  Case 0 : ...\n  Case 1 To 5 : ...\n  Case Else : ...\nEnd Select",
    "Case": "Case label in Select Case.",
    "End Select": "Terminate Select Case block.",
    "For": "For loop (counter-based).\nUsage: For i = 0 To 10 Step 2 : ... : Next",
    "To": "For loop range upper bound.",
    "Step": "For loop increment.",
    "Next": "Terminate For loop.",
    "While": "While loop (pre-test).",
    "Wend": "Terminate While loop.",
    "Do": "Do loop (pre/post-test).",
    "Loop": "Terminate Do loop.",
    "Until": "Loop condition variant.",
    "Exit": "Exit block (loop/function).",
    "Function": "Define function.\nUsage: Function Add(a As Integer, b As Integer) As Integer",
    "Sub": "Define subroutine.",
    "End Function": "Terminate function.",
    "End Sub": "Terminate subroutine.",
    "With": "Create a property context for nested members.\nUsage:\nWith LCD\n  .SetCursor 0, 0\n  .Print \"Hello\"\nEnd With",
    "End With": "Terminate With block.",
    "Return": "Return from function.",
    "Goto": "Jump to label.",
    "Label": "Define jump label.",
    "True": "Boolean true.",
    "False": "Boolean false.",
    "Nothing": "Null reference.",
    "Timer": "Seconds since program start.\nUsage: t = Timer",
    "Randomize": "Seed random number generator.",
    "Round": "Round to nearest integer/precision.\nUsage: y = Round(x, 2)",
    "Fix": "Truncate toward zero.\nUsage: y = Fix(-3.7)  ' -> -3",
    "Sgn": "Sign of number (-1, 0, 1).\nUsage: s = Sgn(x)",
    "Log": "Natural logarithm.\nUsage: y = Log(x)",
    "Exp": "e^x exponential.\nUsage: y = Exp(x)",
    "Atn": "Arctangent.\nUsage: y = Atn(x)",
    "Val": "Parse numeric value from string.",
    "Hex$": "Convert number to hex string.",
    "Oct$": "Convert number to octal string.",
    "Chr$": "Character from code.",
    "Asc": "Code from character.",
    "InStr": "Find substring position.\nUsage: p = InStr(s, \"sub\")",
    "InStrRev": "Find substring position from end.",
    "StrComp": "Compare strings (-1,0,1).",
    "StrReverse": "Reverse string.",
    "Left$": "Left substring.\nUsage: t = Left$(s, 3)",
    "Right$": "Right substring.\nUsage: t = Right$(s, 3)",
    "Mid$": "Substring from position/length.\nUsage: t = Mid$(s, 2, 3)",
    "LCase$": "Lowercase string.\nUsage: t = LCase$(s)",
    "UCase$": "Uppercase string.\nUsage: t = UCase$(s)",
    "Trim$": "Trim whitespace.\nUsage: t = Trim$(s)",
    "Split": "Split string into list by delimiter.\nUsage: arr = Split(\"a,b,c\", \",\")",
    "Join": "Join list into string with delimiter.\nUsage: s = Join(arr, \",\")",
    "Filter": "Filter list by substring.\nUsage: hits = Filter(arr, \"abc\")",
    "UBound": "Upper bound of array.\nUsage: n = UBound(arr)",
    "LBound": "Lower bound of array.\nUsage: n0 = LBound(arr)",
    "Choose": "Pick value by index.\nUsage: v = Choose(i, \"red\", \"green\", \"blue\")",
    "Switch": "Return first matching expression/value.\nUsage: v = Switch(x=0, \"zero\", x<0, \"neg\", True, \"pos\")",
    "RGB": "Compose color from R,G,B.\nUsage: c = RGB(255, 0, 0)",
    "Delay": "Milliseconds delay.",
    "PinMode": "Configure pin mode.\nUsage: PinMode 13, OUTPUT",
    "DigitalWrite": "Write digital output.\nUsage: DigitalWrite 13, HIGH",
    "DigitalRead": "Read digital input.",
    "AnalogWrite": "Write PWM/analog output.\nUsage: AnalogWrite 12, 128",
    "AnalogRead": "Read analog input.\nUsage: v = AnalogRead 34",
    "Serial": "Serial port object.",
    "Serial.begin": "Initialize serial port.\nUsage: Serial.begin 115200",
    "Serial.print": "Print to serial.\nUsage: Serial.print \"Hello\"",
    "Serial.println": "Print line to serial.\nUsage: Serial.println x",
    "setup": "Arduino setup function.",
    "loop": "Arduino loop function.",
}
